In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from util import get_data, plot_data

In [2]:

end_date = "31-12-2009"
start_date = "01-01-2008"
stocks = ["JPM"]

adj_close = get_data((stocks), pd.date_range(start_date, end_date))
adj_close.fillna(method='ffill')
adj_close.fillna(method='bfill')
print adj_close

               SPY    JPM
2008-01-02  132.15  38.47
2008-01-03  132.09  38.20
2008-01-04  128.85  37.33
2008-01-07  128.74  37.71
2008-01-08  126.66  36.21
2008-01-09  127.99  36.72
2008-01-10  128.83  37.70
2008-01-11  127.79  37.27
2008-01-14  128.82  37.73
2008-01-15  125.99  35.73
2008-01-16  124.90  37.79
2008-01-17  121.67  36.52
2008-01-18  120.42  36.11
2008-01-22  119.19  37.27
2008-01-23  122.06  41.70
2008-01-24  123.09  41.01
2008-01-25  121.31  39.81
2008-01-28  123.32  41.57
2008-01-29  123.93  43.28
2008-01-30  123.01  43.19
2008-01-31  125.26  43.24
2008-02-01  127.27  44.01
2008-02-04  125.67  42.16
2008-02-05  122.30  40.03
2008-02-06  121.32  39.88
2008-02-07  122.12  41.15
2008-02-08  121.34  39.97
2008-02-11  121.96  39.54
2008-02-12  123.09  39.51
2008-02-13  124.35  40.23
...            ...    ...
2009-11-18  105.74  41.33
2009-11-19  104.36  40.54
2009-11-20  103.99  40.45
2009-11-23  105.31  41.23
2009-11-24  105.47  40.47
2009-11-25  105.84  40.17
2009-11-27  104.12  39.38
2009-11-30  104.47  40.48
2009-12-01  105.77  40.22
2009-12-02  105.72  39.95
2009-12-03  104.89  39.44
2009-12-04  105.49  39.77
2009-12-07  105.33  39.30
2009-12-08  104.16  39.26
2009-12-09  104.55  39.24
2009-12-10  105.14  39.32
2009-12-11  105.59  39.02
2009-12-14  106.31  39.80
2009-12-15  105.81  38.93
2009-12-16  105.97  39.41
2009-12-17  104.70  38.37
2009-12-18  105.29  39.01
2009-12-21  106.36  39.92
2009-12-22  106.75  39.96
2009-12-23  106.96  39.60
2009-12-24  107.46  39.91
2009-12-28  107.69  39.75
2009-12-29  107.54  39.53
2009-12-30  107.50  39.57
2009-12-31  106.47  39.70

[505 rows x 2 columns]

In [ ]:
adj_close.rolling_m